include: package:pedantic/analysis_options.yaml

# https://www.dartlang.org/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    # - one_member_abstracts
    - slash_for_doc_comments
    # - sort_constructors_first
