name: routeprovider
description: Provides a routing for http-server from dart:io
version: 0.1.0
author: Robert Beyer <4sternrb@googlemail.com>
homepage: http://github.com/4stern/dart-routeprovider
dependencies:
dev_dependencies: