name: route_provider
description: >
  Provides backend routing for http-servers. Split routes into separates parts: authentification, controller for data processing and response for outputting the results.
version: 4.3.0
author: Robert Beyer <4sternrb@googlemail.com>
homepage: https://github.com/4stern/dart-routeprovider
dependencies:
  mime_type: '^0.2.2'
dev_dependencies:
  build_web_compilers: '^2.1.1'
  build_runner: '^1.6.1'
  pedantic: '^1.7.0'
  test: '^1.6.4'
  http: ^0.12.0+2
environment:
  sdk: ">=2.1.0 <3.0.0"
