name: route_provider
description: >
  Provides routing for http-server from dart:io.
version: 2.0.1
author: Robert Beyer <4sternrb@googlemail.com>
homepage: http://github.com/4stern/dart-routeprovider
dependencies:
  mime_type: "^0.2.1"
environment:
  sdk: ">=2.1.0 <3.0.0"
