name: route_provider
description: >
  Provides backend routing for http-server from dart:io.
  Split routes into separates parts: authentification, controller for data processing and response for outputting the results.
  It comes around with a some default responsers for files, folders, json or redirects.
version: 3.1.3
author: Robert Beyer <4sternrb@googlemail.com>
homepage: http://github.com/4stern/dart-routeprovider
dependencies:
  mime_type: "^0.2.2"
dev_dependencies:
  build_web_compilers: '>=0.3.6 <2.0.0'
  build_runner: '>=0.8.10 <2.0.0'
environment:
  sdk: ">=2.1.0 <3.0.0"
