name: route_provider
description: >
  Provides routing for http-server from dart:io.
version: 1.0.0
author: Robert Beyer <4sternrb@googlemail.com>
homepage: http://github.com/4stern/dart-routeprovider
dependencies:
  mime_type: "^0.2.1"
environment:
  sdk: ">=1.8.0 <2.0.0"
