name: route_provider
description: >
  Provides routing for http-server from dart:io.
version: 0.1.10
author: Robert Beyer <4sternrb@googlemail.com>
homepage: http://github.com/4stern/dart-routeprovider
dependencies:
  mime_type: ">=0.1.7 <0.2.0"